const githubResult = """
{
  "total_count": 836,
  "incomplete_results": false,
  "items": [
    {
      "login": "vinicio",
      "id": 874123,
      "node_id": "MDQ6VXNlcjg3NDEyMw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/874123?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vinicio",
      "html_url": "https://github.com/vinicio",
      "followers_url": "https://api.github.com/users/vinicio/followers",
      "following_url": "https://api.github.com/users/vinicio/following{/other_user}",
      "gists_url": "https://api.github.com/users/vinicio/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vinicio/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vinicio/subscriptions",
      "organizations_url": "https://api.github.com/users/vinicio/orgs",
      "repos_url": "https://api.github.com/users/vinicio/repos",
      "events_url": "https://api.github.com/users/vinicio/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vinicio/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "viniciosneves",
      "id": 9221969,
      "node_id": "MDQ6VXNlcjkyMjE5Njk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9221969?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/viniciosneves",
      "html_url": "https://github.com/viniciosneves",
      "followers_url": "https://api.github.com/users/viniciosneves/followers",
      "following_url": "https://api.github.com/users/viniciosneves/following{/other_user}",
      "gists_url": "https://api.github.com/users/viniciosneves/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/viniciosneves/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/viniciosneves/subscriptions",
      "organizations_url": "https://api.github.com/users/viniciosneves/orgs",
      "repos_url": "https://api.github.com/users/viniciosneves/repos",
      "events_url": "https://api.github.com/users/viniciosneves/events{/privacy}",
      "received_events_url": "https://api.github.com/users/viniciosneves/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Vinicios-Pires",
      "id": 98188829,
      "node_id": "U_kgDOBdo-HQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/98188829?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Vinicios-Pires",
      "html_url": "https://github.com/Vinicios-Pires",
      "followers_url": "https://api.github.com/users/Vinicios-Pires/followers",
      "following_url": "https://api.github.com/users/Vinicios-Pires/following{/other_user}",
      "gists_url": "https://api.github.com/users/Vinicios-Pires/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Vinicios-Pires/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Vinicios-Pires/subscriptions",
      "organizations_url": "https://api.github.com/users/Vinicios-Pires/orgs",
      "repos_url": "https://api.github.com/users/Vinicios-Pires/repos",
      "events_url": "https://api.github.com/users/Vinicios-Pires/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Vinicios-Pires/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "VinicioJesus",
      "id": 88550456,
      "node_id": "MDQ6VXNlcjg4NTUwNDU2",
      "avatar_url": "https://avatars.githubusercontent.com/u/88550456?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/VinicioJesus",
      "html_url": "https://github.com/VinicioJesus",
      "followers_url": "https://api.github.com/users/VinicioJesus/followers",
      "following_url": "https://api.github.com/users/VinicioJesus/following{/other_user}",
      "gists_url": "https://api.github.com/users/VinicioJesus/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/VinicioJesus/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/VinicioJesus/subscriptions",
      "organizations_url": "https://api.github.com/users/VinicioJesus/orgs",
      "repos_url": "https://api.github.com/users/VinicioJesus/repos",
      "events_url": "https://api.github.com/users/VinicioJesus/events{/privacy}",
      "received_events_url": "https://api.github.com/users/VinicioJesus/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "vinicioslc",
      "id": 10997022,
      "node_id": "MDQ6VXNlcjEwOTk3MDIy",
      "avatar_url": "https://avatars.githubusercontent.com/u/10997022?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vinicioslc",
      "html_url": "https://github.com/vinicioslc",
      "followers_url": "https://api.github.com/users/vinicioslc/followers",
      "following_url": "https://api.github.com/users/vinicioslc/following{/other_user}",
      "gists_url": "https://api.github.com/users/vinicioslc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vinicioslc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vinicioslc/subscriptions",
      "organizations_url": "https://api.github.com/users/vinicioslc/orgs",
      "repos_url": "https://api.github.com/users/vinicioslc/repos",
      "events_url": "https://api.github.com/users/vinicioslc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vinicioslc/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "viniciosarodrigues",
      "id": 7918549,
      "node_id": "MDQ6VXNlcjc5MTg1NDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7918549?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/viniciosarodrigues",
      "html_url": "https://github.com/viniciosarodrigues",
      "followers_url": "https://api.github.com/users/viniciosarodrigues/followers",
      "following_url": "https://api.github.com/users/viniciosarodrigues/following{/other_user}",
      "gists_url": "https://api.github.com/users/viniciosarodrigues/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/viniciosarodrigues/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/viniciosarodrigues/subscriptions",
      "organizations_url": "https://api.github.com/users/viniciosarodrigues/orgs",
      "repos_url": "https://api.github.com/users/viniciosarodrigues/repos",
      "events_url": "https://api.github.com/users/viniciosarodrigues/events{/privacy}",
      "received_events_url": "https://api.github.com/users/viniciosarodrigues/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lowlevel-1989",
      "id": 8493573,
      "node_id": "MDQ6VXNlcjg0OTM1NzM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8493573?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lowlevel-1989",
      "html_url": "https://github.com/lowlevel-1989",
      "followers_url": "https://api.github.com/users/lowlevel-1989/followers",
      "following_url": "https://api.github.com/users/lowlevel-1989/following{/other_user}",
      "gists_url": "https://api.github.com/users/lowlevel-1989/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lowlevel-1989/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lowlevel-1989/subscriptions",
      "organizations_url": "https://api.github.com/users/lowlevel-1989/orgs",
      "repos_url": "https://api.github.com/users/lowlevel-1989/repos",
      "events_url": "https://api.github.com/users/lowlevel-1989/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lowlevel-1989/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "vinicios-gomes",
      "id": 39882671,
      "node_id": "MDQ6VXNlcjM5ODgyNjcx",
      "avatar_url": "https://avatars.githubusercontent.com/u/39882671?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vinicios-gomes",
      "html_url": "https://github.com/vinicios-gomes",
      "followers_url": "https://api.github.com/users/vinicios-gomes/followers",
      "following_url": "https://api.github.com/users/vinicios-gomes/following{/other_user}",
      "gists_url": "https://api.github.com/users/vinicios-gomes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vinicios-gomes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vinicios-gomes/subscriptions",
      "organizations_url": "https://api.github.com/users/vinicios-gomes/orgs",
      "repos_url": "https://api.github.com/users/vinicios-gomes/repos",
      "events_url": "https://api.github.com/users/vinicios-gomes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vinicios-gomes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "viniciosbastos",
      "id": 9466993,
      "node_id": "MDQ6VXNlcjk0NjY5OTM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9466993?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/viniciosbastos",
      "html_url": "https://github.com/viniciosbastos",
      "followers_url": "https://api.github.com/users/viniciosbastos/followers",
      "following_url": "https://api.github.com/users/viniciosbastos/following{/other_user}",
      "gists_url": "https://api.github.com/users/viniciosbastos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/viniciosbastos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/viniciosbastos/subscriptions",
      "organizations_url": "https://api.github.com/users/viniciosbastos/orgs",
      "repos_url": "https://api.github.com/users/viniciosbastos/repos",
      "events_url": "https://api.github.com/users/viniciosbastos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/viniciosbastos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "viniciosComerciante",
      "id": 28321183,
      "node_id": "MDQ6VXNlcjI4MzIxMTgz",
      "avatar_url": "https://avatars.githubusercontent.com/u/28321183?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/viniciosComerciante",
      "html_url": "https://github.com/viniciosComerciante",
      "followers_url": "https://api.github.com/users/viniciosComerciante/followers",
      "following_url": "https://api.github.com/users/viniciosComerciante/following{/other_user}",
      "gists_url": "https://api.github.com/users/viniciosComerciante/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/viniciosComerciante/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/viniciosComerciante/subscriptions",
      "organizations_url": "https://api.github.com/users/viniciosComerciante/orgs",
      "repos_url": "https://api.github.com/users/viniciosComerciante/repos",
      "events_url": "https://api.github.com/users/viniciosComerciante/events{/privacy}",
      "received_events_url": "https://api.github.com/users/viniciosComerciante/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "undedfined",
      "id": 20071945,
      "node_id": "MDQ6VXNlcjIwMDcxOTQ1",
      "avatar_url": "https://avatars.githubusercontent.com/u/20071945?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/undedfined",
      "html_url": "https://github.com/undedfined",
      "followers_url": "https://api.github.com/users/undedfined/followers",
      "following_url": "https://api.github.com/users/undedfined/following{/other_user}",
      "gists_url": "https://api.github.com/users/undedfined/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/undedfined/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/undedfined/subscriptions",
      "organizations_url": "https://api.github.com/users/undedfined/orgs",
      "repos_url": "https://api.github.com/users/undedfined/repos",
      "events_url": "https://api.github.com/users/undedfined/events{/privacy}",
      "received_events_url": "https://api.github.com/users/undedfined/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Vinicioscastro",
      "id": 61066046,
      "node_id": "MDQ6VXNlcjYxMDY2MDQ2",
      "avatar_url": "https://avatars.githubusercontent.com/u/61066046?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Vinicioscastro",
      "html_url": "https://github.com/Vinicioscastro",
      "followers_url": "https://api.github.com/users/Vinicioscastro/followers",
      "following_url": "https://api.github.com/users/Vinicioscastro/following{/other_user}",
      "gists_url": "https://api.github.com/users/Vinicioscastro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Vinicioscastro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Vinicioscastro/subscriptions",
      "organizations_url": "https://api.github.com/users/Vinicioscastro/orgs",
      "repos_url": "https://api.github.com/users/Vinicioscastro/repos",
      "events_url": "https://api.github.com/users/Vinicioscastro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Vinicioscastro/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "viniciosbarretos",
      "id": 40036992,
      "node_id": "MDQ6VXNlcjQwMDM2OTky",
      "avatar_url": "https://avatars.githubusercontent.com/u/40036992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/viniciosbarretos",
      "html_url": "https://github.com/viniciosbarretos",
      "followers_url": "https://api.github.com/users/viniciosbarretos/followers",
      "following_url": "https://api.github.com/users/viniciosbarretos/following{/other_user}",
      "gists_url": "https://api.github.com/users/viniciosbarretos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/viniciosbarretos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/viniciosbarretos/subscriptions",
      "organizations_url": "https://api.github.com/users/viniciosbarretos/orgs",
      "repos_url": "https://api.github.com/users/viniciosbarretos/repos",
      "events_url": "https://api.github.com/users/viniciosbarretos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/viniciosbarretos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Vinicioslisboa",
      "id": 87781266,
      "node_id": "MDQ6VXNlcjg3NzgxMjY2",
      "avatar_url": "https://avatars.githubusercontent.com/u/87781266?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Vinicioslisboa",
      "html_url": "https://github.com/Vinicioslisboa",
      "followers_url": "https://api.github.com/users/Vinicioslisboa/followers",
      "following_url": "https://api.github.com/users/Vinicioslisboa/following{/other_user}",
      "gists_url": "https://api.github.com/users/Vinicioslisboa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Vinicioslisboa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Vinicioslisboa/subscriptions",
      "organizations_url": "https://api.github.com/users/Vinicioslisboa/orgs",
      "repos_url": "https://api.github.com/users/Vinicioslisboa/repos",
      "events_url": "https://api.github.com/users/Vinicioslisboa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Vinicioslisboa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "viniciosfaustino",
      "id": 7864012,
      "node_id": "MDQ6VXNlcjc4NjQwMTI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7864012?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/viniciosfaustino",
      "html_url": "https://github.com/viniciosfaustino",
      "followers_url": "https://api.github.com/users/viniciosfaustino/followers",
      "following_url": "https://api.github.com/users/viniciosfaustino/following{/other_user}",
      "gists_url": "https://api.github.com/users/viniciosfaustino/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/viniciosfaustino/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/viniciosfaustino/subscriptions",
      "organizations_url": "https://api.github.com/users/viniciosfaustino/orgs",
      "repos_url": "https://api.github.com/users/viniciosfaustino/repos",
      "events_url": "https://api.github.com/users/viniciosfaustino/events{/privacy}",
      "received_events_url": "https://api.github.com/users/viniciosfaustino/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "VinicioCabrera",
      "id": 49033433,
      "node_id": "MDQ6VXNlcjQ5MDMzNDMz",
      "avatar_url": "https://avatars.githubusercontent.com/u/49033433?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/VinicioCabrera",
      "html_url": "https://github.com/VinicioCabrera",
      "followers_url": "https://api.github.com/users/VinicioCabrera/followers",
      "following_url": "https://api.github.com/users/VinicioCabrera/following{/other_user}",
      "gists_url": "https://api.github.com/users/VinicioCabrera/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/VinicioCabrera/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/VinicioCabrera/subscriptions",
      "organizations_url": "https://api.github.com/users/VinicioCabrera/orgs",
      "repos_url": "https://api.github.com/users/VinicioCabrera/repos",
      "events_url": "https://api.github.com/users/VinicioCabrera/events{/privacy}",
      "received_events_url": "https://api.github.com/users/VinicioCabrera/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "vinicios-santos",
      "id": 95624273,
      "node_id": "U_kgDOBbMcUQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/95624273?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vinicios-santos",
      "html_url": "https://github.com/vinicios-santos",
      "followers_url": "https://api.github.com/users/vinicios-santos/followers",
      "following_url": "https://api.github.com/users/vinicios-santos/following{/other_user}",
      "gists_url": "https://api.github.com/users/vinicios-santos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vinicios-santos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vinicios-santos/subscriptions",
      "organizations_url": "https://api.github.com/users/vinicios-santos/orgs",
      "repos_url": "https://api.github.com/users/vinicios-santos/repos",
      "events_url": "https://api.github.com/users/vinicios-santos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vinicios-santos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "viniciosragazzi",
      "id": 73366668,
      "node_id": "MDQ6VXNlcjczMzY2NjY4",
      "avatar_url": "https://avatars.githubusercontent.com/u/73366668?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/viniciosragazzi",
      "html_url": "https://github.com/viniciosragazzi",
      "followers_url": "https://api.github.com/users/viniciosragazzi/followers",
      "following_url": "https://api.github.com/users/viniciosragazzi/following{/other_user}",
      "gists_url": "https://api.github.com/users/viniciosragazzi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/viniciosragazzi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/viniciosragazzi/subscriptions",
      "organizations_url": "https://api.github.com/users/viniciosragazzi/orgs",
      "repos_url": "https://api.github.com/users/viniciosragazzi/repos",
      "events_url": "https://api.github.com/users/viniciosragazzi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/viniciosragazzi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MaksonViini",
      "id": 51179463,
      "node_id": "MDQ6VXNlcjUxMTc5NDYz",
      "avatar_url": "https://avatars.githubusercontent.com/u/51179463?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MaksonViini",
      "html_url": "https://github.com/MaksonViini",
      "followers_url": "https://api.github.com/users/MaksonViini/followers",
      "following_url": "https://api.github.com/users/MaksonViini/following{/other_user}",
      "gists_url": "https://api.github.com/users/MaksonViini/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MaksonViini/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MaksonViini/subscriptions",
      "organizations_url": "https://api.github.com/users/MaksonViini/orgs",
      "repos_url": "https://api.github.com/users/MaksonViini/repos",
      "events_url": "https://api.github.com/users/MaksonViini/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MaksonViini/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "vinicioslop",
      "id": 42284656,
      "node_id": "MDQ6VXNlcjQyMjg0NjU2",
      "avatar_url": "https://avatars.githubusercontent.com/u/42284656?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vinicioslop",
      "html_url": "https://github.com/vinicioslop",
      "followers_url": "https://api.github.com/users/vinicioslop/followers",
      "following_url": "https://api.github.com/users/vinicioslop/following{/other_user}",
      "gists_url": "https://api.github.com/users/vinicioslop/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vinicioslop/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vinicioslop/subscriptions",
      "organizations_url": "https://api.github.com/users/vinicioslop/orgs",
      "repos_url": "https://api.github.com/users/vinicioslop/repos",
      "events_url": "https://api.github.com/users/vinicioslop/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vinicioslop/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "VinRicci",
      "id": 38709170,
      "node_id": "MDQ6VXNlcjM4NzA5MTcw",
      "avatar_url": "https://avatars.githubusercontent.com/u/38709170?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/VinRicci",
      "html_url": "https://github.com/VinRicci",
      "followers_url": "https://api.github.com/users/VinRicci/followers",
      "following_url": "https://api.github.com/users/VinRicci/following{/other_user}",
      "gists_url": "https://api.github.com/users/VinRicci/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/VinRicci/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/VinRicci/subscriptions",
      "organizations_url": "https://api.github.com/users/VinRicci/orgs",
      "repos_url": "https://api.github.com/users/VinRicci/repos",
      "events_url": "https://api.github.com/users/VinRicci/events{/privacy}",
      "received_events_url": "https://api.github.com/users/VinRicci/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Vinicios13",
      "id": 33033163,
      "node_id": "MDQ6VXNlcjMzMDMzMTYz",
      "avatar_url": "https://avatars.githubusercontent.com/u/33033163?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Vinicios13",
      "html_url": "https://github.com/Vinicios13",
      "followers_url": "https://api.github.com/users/Vinicios13/followers",
      "following_url": "https://api.github.com/users/Vinicios13/following{/other_user}",
      "gists_url": "https://api.github.com/users/Vinicios13/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Vinicios13/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Vinicios13/subscriptions",
      "organizations_url": "https://api.github.com/users/Vinicios13/orgs",
      "repos_url": "https://api.github.com/users/Vinicios13/repos",
      "events_url": "https://api.github.com/users/Vinicios13/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Vinicios13/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Viniart",
      "id": 72676428,
      "node_id": "MDQ6VXNlcjcyNjc2NDI4",
      "avatar_url": "https://avatars.githubusercontent.com/u/72676428?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Viniart",
      "html_url": "https://github.com/Viniart",
      "followers_url": "https://api.github.com/users/Viniart/followers",
      "following_url": "https://api.github.com/users/Viniart/following{/other_user}",
      "gists_url": "https://api.github.com/users/Viniart/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Viniart/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Viniart/subscriptions",
      "organizations_url": "https://api.github.com/users/Viniart/orgs",
      "repos_url": "https://api.github.com/users/Viniart/repos",
      "events_url": "https://api.github.com/users/Viniart/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Viniart/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ViniciosLugli",
      "id": 40807526,
      "node_id": "MDQ6VXNlcjQwODA3NTI2",
      "avatar_url": "https://avatars.githubusercontent.com/u/40807526?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ViniciosLugli",
      "html_url": "https://github.com/ViniciosLugli",
      "followers_url": "https://api.github.com/users/ViniciosLugli/followers",
      "following_url": "https://api.github.com/users/ViniciosLugli/following{/other_user}",
      "gists_url": "https://api.github.com/users/ViniciosLugli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ViniciosLugli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ViniciosLugli/subscriptions",
      "organizations_url": "https://api.github.com/users/ViniciosLugli/orgs",
      "repos_url": "https://api.github.com/users/ViniciosLugli/repos",
      "events_url": "https://api.github.com/users/ViniciosLugli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ViniciosLugli/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "DiegoVinicio103",
      "id": 74928178,
      "node_id": "MDQ6VXNlcjc0OTI4MTc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/74928178?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DiegoVinicio103",
      "html_url": "https://github.com/DiegoVinicio103",
      "followers_url": "https://api.github.com/users/DiegoVinicio103/followers",
      "following_url": "https://api.github.com/users/DiegoVinicio103/following{/other_user}",
      "gists_url": "https://api.github.com/users/DiegoVinicio103/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DiegoVinicio103/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DiegoVinicio103/subscriptions",
      "organizations_url": "https://api.github.com/users/DiegoVinicio103/orgs",
      "repos_url": "https://api.github.com/users/DiegoVinicio103/repos",
      "events_url": "https://api.github.com/users/DiegoVinicio103/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DiegoVinicio103/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "hectorlopezv",
      "id": 46845790,
      "node_id": "MDQ6VXNlcjQ2ODQ1Nzkw",
      "avatar_url": "https://avatars.githubusercontent.com/u/46845790?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/hectorlopezv",
      "html_url": "https://github.com/hectorlopezv",
      "followers_url": "https://api.github.com/users/hectorlopezv/followers",
      "following_url": "https://api.github.com/users/hectorlopezv/following{/other_user}",
      "gists_url": "https://api.github.com/users/hectorlopezv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/hectorlopezv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hectorlopezv/subscriptions",
      "organizations_url": "https://api.github.com/users/hectorlopezv/orgs",
      "repos_url": "https://api.github.com/users/hectorlopezv/repos",
      "events_url": "https://api.github.com/users/hectorlopezv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/hectorlopezv/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "viniciosgois",
      "id": 43430041,
      "node_id": "MDQ6VXNlcjQzNDMwMDQx",
      "avatar_url": "https://avatars.githubusercontent.com/u/43430041?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/viniciosgois",
      "html_url": "https://github.com/viniciosgois",
      "followers_url": "https://api.github.com/users/viniciosgois/followers",
      "following_url": "https://api.github.com/users/viniciosgois/following{/other_user}",
      "gists_url": "https://api.github.com/users/viniciosgois/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/viniciosgois/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/viniciosgois/subscriptions",
      "organizations_url": "https://api.github.com/users/viniciosgois/orgs",
      "repos_url": "https://api.github.com/users/viniciosgois/repos",
      "events_url": "https://api.github.com/users/viniciosgois/events{/privacy}",
      "received_events_url": "https://api.github.com/users/viniciosgois/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ViniciosF",
      "id": 85592192,
      "node_id": "MDQ6VXNlcjg1NTkyMTky",
      "avatar_url": "https://avatars.githubusercontent.com/u/85592192?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ViniciosF",
      "html_url": "https://github.com/ViniciosF",
      "followers_url": "https://api.github.com/users/ViniciosF/followers",
      "following_url": "https://api.github.com/users/ViniciosF/following{/other_user}",
      "gists_url": "https://api.github.com/users/ViniciosF/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ViniciosF/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ViniciosF/subscriptions",
      "organizations_url": "https://api.github.com/users/ViniciosF/orgs",
      "repos_url": "https://api.github.com/users/ViniciosF/repos",
      "events_url": "https://api.github.com/users/ViniciosF/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ViniciosF/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ViniciosCoelho",
      "id": 14830130,
      "node_id": "MDQ6VXNlcjE0ODMwMTMw",
      "avatar_url": "https://avatars.githubusercontent.com/u/14830130?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ViniciosCoelho",
      "html_url": "https://github.com/ViniciosCoelho",
      "followers_url": "https://api.github.com/users/ViniciosCoelho/followers",
      "following_url": "https://api.github.com/users/ViniciosCoelho/following{/other_user}",
      "gists_url": "https://api.github.com/users/ViniciosCoelho/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ViniciosCoelho/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ViniciosCoelho/subscriptions",
      "organizations_url": "https://api.github.com/users/ViniciosCoelho/orgs",
      "repos_url": "https://api.github.com/users/ViniciosCoelho/repos",
      "events_url": "https://api.github.com/users/ViniciosCoelho/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ViniciosCoelho/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "vladimirsan",
      "id": 381239,
      "node_id": "MDQ6VXNlcjM4MTIzOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/381239?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vladimirsan",
      "html_url": "https://github.com/vladimirsan",
      "followers_url": "https://api.github.com/users/vladimirsan/followers",
      "following_url": "https://api.github.com/users/vladimirsan/following{/other_user}",
      "gists_url": "https://api.github.com/users/vladimirsan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vladimirsan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vladimirsan/subscriptions",
      "organizations_url": "https://api.github.com/users/vladimirsan/orgs",
      "repos_url": "https://api.github.com/users/vladimirsan/repos",
      "events_url": "https://api.github.com/users/vladimirsan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vladimirsan/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""";